---
apiVersion: v1
kind: Service
metadata:
  name: germainapm-kafka
spec:
  clusterIP: None
  selector:
    app: kafka
  ports:
    - name: germainapm-kafka-port
      port: 9092
      protocol: TCP
      targetPort: kafka-port

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka
spec:
  replicas: {{kafkaReplicas}}
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      containers:
        - image: docker.io/bitnami/kafka:{{kafkaVersion}}
          imagePullPolicy: Always
          name: kafka
          resources:
            requests:
              memory: 512Mi
              cpu: 100m
            limits:
              memory: 2048Mi
              cpu: 1000m
          ports:
            - containerPort: 9092
              name: kafka-port
          env:
            - name: KAFKA_CFG_NODE_ID
              value: "0"
            - name: KAFKA_CFG_PROCESS_ROLES
              value: "controller,broker"
            - name: KAFKA_CFG_CONTROLLER_QUORUM_VOTERS
              value: "0@localhost:9093"
            - name: KAFKA_CFG_LISTENERS
              value: "PLAINTEXT://:9092,CONTROLLER://:9093"
            - name: KAFKA_CFG_ADVERTISED_LISTENERS
              value: "PLAINTEXT://localhost:9092"
            - name: KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP
              value: "CONTROLLER:PLAINTEXT,EXTERNAL:PLAINTEXT,PLAINTEXT:PLAINTEXT"
            - name: KAFKA_CFG_CONTROLLER_LISTENER_NAMES
              value: "CONTROLLER"