
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zkdata-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zkdata-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zkdatalogs-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: zkdatalogs-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: germainapm-zookeeper
  labels:
    app: zookeeper
spec:
  ports:
  - port: 2181
    name: client
  clusterIP: None
  selector:
    app: zookeeper

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - image: zookeeper:{{zookeeperVersion}}
        name: zookeeper
        env:
        - name: JVMFLAGS
          value: "-Xms256m -Xmx768m"
        ports:
        - containerPort: 2181
          name: zookeeper
        volumeMounts:
        - name: zkdata-persistent-storage
          mountPath: /data
        - name: zkdatalogs-persistent-storage
          mountPath: /datalog
      volumes:
      - name: zkdata-persistent-storage
        persistentVolumeClaim:
          claimName: zkdata-pv-claim
      - name: zkdatalogs-persistent-storage
        persistentVolumeClaim:
          claimName: zkdatalogs-pv-claim
